# Mean Absolute error

## Using Function

In [8]:
import numpy as np 

y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [9]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print('Total error: ', total_error)
    
    mae = total_error/ len(y_predicted)
    print('Mae: ', mae)
#     return mae

In [10]:
mae(y_true, y_predicted)

Total error:  2.5
Mae:  0.5


## Using Numpy array operation

In [11]:
np.mean(np.abs(y_true - y_predicted))

0.5

In [12]:
np.sum(np.abs(y_true - y_predicted))

2.5

# log loss / binary_crossentropy

In [21]:
np.log(y_predicted)

C:\Users\sabir\AppData\Local\Temp\ipykernel_8820\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [14]:
## log of 0 is undefined thats why make all the values in y_predicted such that any subtraction from y_true will not give
## the value zero..... and for that we use epsilon

In [15]:
epsilon = 1e-15

In [20]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
print(y_predicted)
print(y_predicted_new)

[1 1 0 0 1]
[1, 1, 1e-15, 1e-15, 1]


In [18]:
y_predicted_new2 = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new2

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [23]:
type(y_predicted_new2)

list

In [24]:
y_predicted_new2 = np.array(y_predicted_new2)
np.log(y_predicted_new2)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [25]:
-np.mean(y_true*np.log(y_predicted_new2)+(1-y_true)*np.log(1-y_predicted_new2))

17.2696280766844

In [26]:
## all the above operations in one single fucntion

In [29]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new2)+(1-y_true)*np.log(1-y_predicted_new2))

In [30]:
log_loss(y_true, y_predicted)

17.2696280766844